config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  post 'contacts/create'
  devise_for :users
  resources :articles
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user,optional: true

  validates :title, presence: true
  validates :subtitle, presence: true
  validates :body, presence: true

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, length: {maximum:255}, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :message, presence: true

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile,dependent: :destroy
  has_many :articles, dependent: :destroy

  # validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:edit, :update, :destro]

  def index
    @articles = Article.order(created_at: :desc)
    @articles = Article.page(params[:page]).per(8)
  end

  def show

  end

  def edit
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Post completed!'
    else
      render :new, alert: 'Post failed..'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Update completed!'
    else
      render :edit, alert: 'Update failed..'
    end
  end

  def destroy
    @article.destroy
    if @article.destroy
      redirect_to root_path, notice: 'Delete completed!'
    else
      redirect_to root_path, alert: 'Delete failed..'

    end
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :subtitle, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      flash[:notice] = '送信ありがとうございました。'
      redirect_to root_path
    else
      flash[:alert] = '入力に不備があります。'
      render :new

    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :subtitle, 'SubTitle' %>
    <%= f.text_field :subtitle, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, 'Body' %>
    <%= f.text_area :body, class: 'form-control',rows: 10 %>
  </div>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/articles/edit.html.erb
<header class="masthead" style="background-image: url('/images/writing-1209121_1280.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1 class="text-center">
            Edit Post
          </h1>
        </div>
      </div>
    </div>
  </div>
</header>

<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <%= render 'form', article: @article %>
      </div>
    </div>
  </div>
</article>

app/views/articles/index.html.erb
<header class="masthead" style="background-image: url('/images/home-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>Irikawa's Blog</h1>
          <span class="subheading">駆け出しエンジニアの備忘録</span>
        </div>
      </div>
    </div>
  </div>
</header>


<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <% @articles.each do |article| %>
        <%= link_to article do %>
          <div class="post-preview">

            <h2 class="post-title">
              <%= article.title %>
            </h2>
            <h3 class="post-subtitle">
              <%= article.subtitle %>
            </h3>
            <p class="post-meta">Posted by
              <%= link_to 't.irikawa', root_path %>
              <%= article.created_at.strftime("%Y年%m月%d日") %>
            </p>

          </div>
        <% end %>
      <% end %>
      <hr>

      <!-- Pager -->
<!--      <div class="clearfix">-->
        <%= paginate @articles %>
        <%#= link_to_next_page @articles,'Older Posts',class:"btn btn-primary float-right" %>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<header class="masthead" style="background-image: url('/images/writing-1209121_1280.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1 class="text-center">
            Create Post
          </h1>
        </div>
      </div>
    </div>
  </div>
</header>

<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <%= render 'form', article: @article, locals:{btn_name:'Create'} %>
      </div>
    </div>
  </div>
</article>

app/views/articles/show.html.erb
<header class="masthead" style="background-image: url('/images/post-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1>
            <%=  @article.title %>
          </h1>
          <h2 class="subheading">
            <%= @article.subtitle %>
          </h2>
          <span class="meta">Posted by
            <%= link_to 't.irikawa', root_path %>
            <%= @article.created_at.strftime("%Y年%m月%d日") %></span>
        </div>
      </div>
    </div>
  </div>
</header>

<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>
          <%= simple_format @article.body %>
        </p>
        <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-success' %>
        <%= link_to 'Delete', article_path(@article), data: {confirm: '削除してもよろしいですか？'}, method: :delete, class: 'btn btn-danger' %>
      </div>
    </div>

  </div>
</article>

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/new.html.erb
<header class="masthead" style="background-image: url('/images/contact-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="page-heading">
          <h1>Contact Me</h1>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <p>下記ご入力いただき、お気軽にご連絡ください。</p>
      <%= form_for @contact, url: contacts_create_path do |f| %>
        <div class="form-group">
          <%= f.label :name, 'Name' %>
          <%= f.text_field :name, class:'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email, 'Mail' %>
          <%= f.text_field :email, class:'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :message, 'Message' %>
          <%= f.text_area :message, class: 'form-control',rows: 10 %>
        </div>
        <%= f.submit 'Send', class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
      <% if user_signed_in? %>
        <%= link_to 'StartRails', root_path, class: "navbar-brand" %>
      <% else %>
        <%= link_to 'Guest', root_path, class: "navbar-brand" %>
      <% end %>

      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <%= fa_icon "bars" %>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'About', page_path('about'), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Contact', contacts_new_path, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Create', new_article_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "navbar-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Signup', new_user_registration_path, class: "navbar-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Login', new_user_session_path, class: "navbar-link" %>
            </li>
          <% end %>
          </li>
        </ul>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Irikawa'sBlog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application','clean-blog', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
<!-- Navigation -->

  <%= render 'layouts/header' %>

<%= yield %>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="https://twitter.com/indy33817719">
                  <span>
                    <%= fa_stacked_icon "twitter", base: "circle", class: "fa-lg",icon_options: { class: "text-light" } %>
                  </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
        </div>
      </div>
    </div>
  </footer>

  <div class="notifications">
    <% flash.each do |key,value| %>
      <%= content_tag(:div, value, class: key) %>
    <% end %>
  </div>

</body>

</html>

app/views/pages/about.html.erb
<header class="masthead" style="background-image: url('/images/about-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1 class="text-center">
            About me
          </h1>
        </div>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="row">
    <table class="table table-striped">
      <tr>
        <th>Name</th>
        <td>入川 知之（イリカワ トモユキ）</td>
      </tr>
      <tr>
        <th>Age</th>
        <td>27</td>
      </tr>
      <tr>
        <th>Place</th>
        <td>大宮→横浜→宇都宮→十条（現在は妻と2人暮らし）</td>
      </tr>
      <tr>
        <th>Career</th>
        <td>2015/4〜2016/10：建材系商社の住宅事業部に営業職として従事<br/>
          2016/11〜現在：SIerの金融営業部に営業職として従事<br/>
          業務内容は、金融機関様を向けにインフラに係る製品・サービス販売。<br/>
          2018年度に個人成績を前年度比で約230%伸ばし、若手部門社長賞を受賞。<br/>
          営業部としては未着手の部分であった「サーバーサイジングチーム」を設立する等、<br/>
          社内体制の改善に主体的に取り組んでおります。
          </td>
      </tr>
      <tr>
        <th>qualification</th>
        <td>TOEIC（670点）→800点を目標に学習中。<br/>
          宅地建物取引士<br/>
          ITパスポート<br/>
          日商簿記3級<br/>
          いずれも社会人になってから取得。色々な分野を幅広く勉強してきました。<br/>
          新しいことを学ぶことが好きで、継続して勉強することが得意です。
        </td>
      </tr>
      <tr>
        <th>Trigger</th>
        <td>開発系の案件に携わった際に、<br/>
            「営業職でもプログラミングを知っていた方が話ができるでは？」<br/>
            と思い、プログラミング学習を開始。<br/>
          以降どハマりし、エンジニアになるため日々勉強中。<br/>
          2019/11〜現在：渋谷コード塾に入塾。html/css/ruby/railsを学習。reactも学習予定。
          2020/5〜：エンジニアとして働き始める（目標！）
        </td>
      </tr>
    </table>
  </div>
</div>
</div>